Jordi/cf 453 enable auto complete on the cli
common-fate/granted-cli pull request #15
Opened 2022-01-28 07:14 UTC by jordiup

2022-01-28 07:37 UTC, jordiup commented
# Testing with various shells 

Firstly run make cli, this will push autocompletion scripts to your usr/local/bin

Then you can source the scripts by running the below (or adding them to your .zshrc)

### Bash

`PROG=dgranted source /usr/local/bin/granted_completer_bash `

### Zsh

`PROG=dgranted source /usr/local/bin/granted_completer_zsh`

### Fish 

`source ~/.config/fish/completions/granted_completer_fish.fish `

2022-01-28 13:26 UTC, chrnorm requested changes

2022-01-28 13:26 UTC, chrnorm commented on Makefile
> +	rm ~/.config/fish/conf.d
FYI `~/.config/fish/conf.d` is a directory for me (I use fish as my regular console rather than ZSH). The `rm` command won't work and we should probably not delete this anyway as the `conf.d` folder contains other installed scripts, not only Granted stuff.

```suggestion

```

2022-01-28 13:26 UTC, chrnorm commented on cmd/cli/main.go
> +// To add more methods to the CLI app, add them to internal/granted_cli
minor nitpick

```suggestion
// To add more methods to the CLI app, add them to cmd/cli/setup/granted_cli.go
```

2022-01-28 13:26 UTC, chrnorm commented on pkg/providers/ensure_updated.go
> +	// client.ListRoles()
nitpick we can remove these
```suggestion
	// client.ListMembers()
	// @TODO: make me work!
	// client.ListRoles()
```

2022-01-28 13:26 UTC, chrnorm commented on cmd/dev/generate_fish_completion.go
> +
For now, we could just make fish the only supported argument in `granted autocomplete install`. If any other argument is provided (e.g. `granted autocomplete install --shell=bash`, the CLI can just link the user to a docs URL which instructs them on how to set up the sourcing in their bash profile)

2022-01-28 13:26 UTC, chrnorm commented on cmd/cli/main.go
> +	app := setup.GetCliApp()
If we implement my suggestion in my comment on `cmd/dev/generate_fish_completion.go`, we won't need `GetCliApp` as a separate method and can just move the CLI setup back into `cmd/cli/main.go` rather than having it as a separate file

2022-02-01 09:07 UTC, jordiup commented on cmd/dev/generate_fish_completion.go
> +
Cheers Chris, this is definitely something we can do

I ruled it out initially just to save time 

[I've done a write up here that explains how Github CLI implemented this UX pattern using Cobra](https://www.notion.so/exponentlabs/Some-more-thoughts-on-autocomplete-ef0fec7f61b94ede979b6c8e876ba846)

I'll work on these amendments this evening/tomorrow

2022-02-03 01:58 UTC, merged