Jordi/cf 407 no way for users to list roles they have
common-fate/granted-cli pull request #8
Opened 2022-01-21 08:24 UTC by jordiup

Just a draft PR up for now, see ticket here

2022-01-24 16:37 UTC, chrnorm requested changes

2022-01-24 16:37 UTC, chrnorm commented on cmd/assume/main.go
> +				providerId: "aws",
It's possible for users to set providers other than `aws` (in fact, provider IDs can be any string). We should handle this rather than hardcoding the provider ID to "aws"

2022-01-24 16:37 UTC, chrnorm commented on cmd/assume/main.go
> +		account = "aws:" + roleOptionMap[roleacc].customerId
Same as above - provider IDs are defined by the user when they set up Granted

2022-01-25 05:44 UTC, jordiup commented on cmd/assume/main.go
> +				providerId: "aws",
Should be all good now, using a dynamic provider id 👌

2022-01-25 05:44 UTC, merged